### ISSUE TITLE
Windowmasker/ustat and windowmasker/mk_counts crash yaml collection

### ISSUE THREAD

**Issue by DLBPointon** [nf-core/modules#3236]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

The windowmasker modules I made, when tested in isolation work perfectly, however in a pipeline they will cause the `CUSTOM_DUMPSOFTWAREVERSIONS` module to crash with the below error.

Caused by the version data for windowmasker outputting a mapped object, e.g., `windowmasker : 1.0.0` so the yaml collects 'windowmasker: windowmasker : 1.0.0`.

@alxndrdiaz has a must better version collection string:
```
        windowmasker: \$(windowmasker -version-full | head -n 1 | sed 's/^.*windowmasker: //; s/ .*\$//')
```

I'll submit a PR for this today.

### Command used and terminal output

```console
bsub -Is -tty -e error -o out -n 2 -q normal -M40000 -R'select[mem>40000] rusage[mem=40000] span[hosts=1]' 'nextflow run main.nf -profile singularity,sanger --input ASSEMBLY_YAML/testing.yaml --outdir test-2023-03-27.dp24.TEST -resume'
```

```
Command error:
  Traceback (most recent call last):
    File ".command.sh", line 101, in <module>
      main()
    File ".command.sh", line 61, in main
      versions_by_process = yaml.load(f, Loader=yaml.BaseLoader) | versions_this_module
    File "/usr/local/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
      return loader.get_single_data()
    File "/usr/local/lib/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
      node = self.get_single_node()
    File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 36, in get_single_node
      document = self.compose_document()
    File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 55, in compose_document
      node = self.compose_node(None, None)
    File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
      node = self.compose_mapping_node(anchor)
    File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 133, in compose_mapping_node
      item_value = self.compose_node(node, item_key)
    File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 84, in compose_node
      node = self.compose_mapping_node(anchor)
    File "/usr/local/lib/python3.10/site-packages/yaml/composer.py", line 127, in compose_mapping_node
      while not self.check_event(MappingEndEvent):
    File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 98, in check_event
      self.current_event = self.state()
    File "/usr/local/lib/python3.10/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
      if self.check_token(KeyToken):
    File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 116, in check_token
      self.fetch_more_tokens()
    File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
      return self.fetch_value()
    File "/usr/local/lib/python3.10/site-packages/yaml/scanner.py", line 577, in fetch_value
      raise ScannerError(None, None,
  yaml.scanner.ScannerError: mapping values are not allowed here
    in "collated_versions.yml", line 23, column 31

Work dir:
  /lustre/scratch123/DIRECTORY/treeval/work/e6/389557022e5fa61a63ff929bf6603b
```
```


### Relevant files

_No response_

### System information

_No response_

**Comment by DLBPointon** [comment]
This was merged, last week.
