### ISSUE TITLE
Module stub that `touch .gz` break snapshots in `nf-test`

### ISSUE THREAD

**Issue by awgymer** [nf-core/modules#5409]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

Per [this slack thread](https://nfcore.slack.com/archives/C049MBCEW06/p1711576470656399) it seems that empty `.gz` files generated by simply `touch <filename>.gz` break the snapshot functionality of `nf-test` by causing an `EOFException` because the files are not actually compressed.

Per [this comment](https://nfcore.slack.com/archives/C06P9UP3K4G/p1710936665174999?thread_ts=1710933144.723739&cid=C06P9UP3K4G) a fix is to replace the `touch` command with `echo "" | gzip > <filename>.gz`.

A `git grep touch .*\.gz` identifies the following 96 modules as using this pattern:

- [] arriba/download
- [] art/illumina
- [] bcftools/call
- [] bcftools/concat
- [] bcftools/split
- [] bedgovcf
- [] bowtie2/align
- [] cadd
- [] cat/fastq
- [] cellrangerarc/mkfastq
- [] cellrangeratac/mkfastq
- [] clustalo/align
- [] deepvariant
- [] delly/call
- [] ensemblvep/vep
- [] expansionhunter
- [] famsa/align
- [] fastp
- [] fcs/fcsadaptor
- [] gatk4/applyvqsr
- [] gatk4/filtermutectcalls
- [] gatk4/genotypegvcfs
- [] gatk4/haplotypecaller
- [] gatk4/mergevcfs
- [] gatk4/mutect2
- [] gatk4/postprocessgermlinecnvcalls
- [] gatk4/reblockgvcf
- [] gatk4/samtofastq
- [] gatk4/selectvariants
- [] gatk4/variantfiltration
- [] genomad/endtoend
- [] getorganelle/fromreads
- [] gfastats
- [] gfatools/gfa2fa
- [] glimpse/concordance
- [] glimpse2/concordance
- [] goleft/indexcov
- [] gridss/gridss
- [] happy/happy
- [] icountmini/peaks
- [] icountmini/sigxls
- [] jasminesv
- [] kalign/align
- [] kmcp/search
- [] learnmsa/align
- [] lofreq/somatic
- [] mafft
- [] manta/germline
- [] manta/somatic
- [] manta/tumoronly
- [] mosdepth
- [] mtmalign/align
- [] muscle5/super5
- [] nanofilt
- [] ngmerge
- [] parabricks/indexgvcf
- [] parabricks/mutectcaller
- [] paragraph/multigrmpy
- [] paragraph/vcf2paragraph
- [] pharokka/installdatabases
- [] picard/extractfingerprint
- [] picard/liftovervcf
- [] picard/renamesampleinvcf
- [] picard/sortvcf
- [] popscle/dscpileup
- [] prodigal
- [] purecn/coverage
- [] pyrodigal
- [] rtgtools/vcfeval
- [] sentieon/applyvarcal
- [] sentieon/dnamodelapply
- [] sentieon/dnascope
- [] sentieon/gvcftyper
- [] sentieon/haplotyper
- [] sentieon/tnfilter
- [] sentieon/tnhaplotyper2
- [] sentieon/tnscope
- [] seqkit/grep
- [] shapeit5/switch
- [] sortmerna
- [] star/align
- [] stitch
- [] stranger
- [] strelka/germline
- [] strelka/somatic
- [] svaba
- [] svanalyzer/svbenchmark
- [] svdb/merge
- [] tabix/bgzip
- [] tabix/bgziptabix
- [] tcoffee/align
- [] truvari/bench
- [] vcflib/vcfbreakmulti
- [] vt/decompose
- [] vt/normalize
- [] wittyer

**Comment by famosab** [comment]
For wittyer the code in the stub test actually looks like this:
```
    touch ${prefix}.json
    echo | gzip > ${prefix}.vcf.gz
    touch ${prefix}.vcf.gz.tbi
 ```
When I tested the module using touch to create the `.gz.tbi` file did not lead to errors when asserting `{ assert snapshot(process.out).match() }`, so it seems to me that you would only need to search for modules where the file extension ends with `.gz`.

**Comment by awgymer** [comment]
The list was generated before I had tested `.gz.*` type files. It does indeed seem that these are not an issue for `nf-test` (I think it does a naive check for `.gz` file extension before it tries opening as a gzipped file?). 

I've revised the list with a regex that excludes such files.

**Comment by scorreard** [comment]
Trying to update them all at once instead of doing it individually. It should address most of the modules issues

**Comment by famosab** [comment]
Problem with pharokka:

```bash
     pharokka.py \
        --infile genome.fasta \
        --outdir test_pharokka \
        --database pharokka_db \
        --threads 2 \
        --prefix test \
        --fast --skip_extra_annotations --skip_mash
    
    cat <<-END_VERSIONS > versions.yml
    "PHAROKKA_PHAROKKA":
        pharokka: $(pharokka.py --version)
    END_VERSIONS
  
  Command exit status:
    1
  
  Command output:
    (empty)
  
  Command error:
    /home/runner/_work/modules/modules/.nf-test/tests/f4ff6f3ff2c31cdd0ae0bfea1540e4f4/work/conda/env-59d3ccaaf552043f-38590c47211f7272b7570db0336b1682/lib/python3.10/site-packages/numpy/_core/getlimits.py:558: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
      setattr(self, word, getattr(machar, word).flat[0])
    /home/runner/_work/modules/modules/.nf-test/tests/f4ff6f3ff2c31cdd0ae0bfea1540e4f4/work/conda/env-59d3ccaaf552043f-38590c47211f7272b7570db0336b1682/lib/python3.10/site-packages/numpy/_core/getlimits.py:90: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
      return self._float_to_str(self.smallest_subnormal)
    /home/runner/_work/modules/modules/.nf-test/tests/f4ff6f3ff2c31cdd0ae0bfea1540e4f4/work/conda/env-59d3ccaaf552043f-38590c47211f7272b7570db0336b1682/lib/python3.10/site-packages/numpy/_core/getlimits.py:558: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
      setattr(self, word, getattr(machar, word).flat[0])
    /home/runner/_work/modules/modules/.nf-test/tests/f4ff6f3ff2c31cdd0ae0bfea1540e4f4/work/conda/env-59d3ccaaf552043f-38590c47211f7272b7570db0336b1682/lib/python3.10/site-packages/numpy/_core/getlimits.py:90: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
      return self._float_to_str(self.smallest_subnormal)
    2025-08-11 11:35:43.687 | INFO     | __main__:main:95 - Starting Pharokka v1.7.3
    2025-08-11 11:35:43.687 | INFO     | __main__:main:96 - Command executed: Namespace(infile='genome.fasta', outdir='test_pharokka', database='pharokka_db', threads='2', force=False, prefix='test', locustag='Default', gene_predictor='default', meta=False, split=False, coding_table='11', evalue='1E-05', fast=True, mmseqs2_only=False, meta_hmm=False, dnaapler=False, custom_hmm='', genbank=False, terminase=False, terminase_strand='nothing', terminase_start='nothing', skip_extra_annotations=True, skip_mash=True, minced_args='', mash_distance=0.2, citation=False)
    2025-08-11 11:35:43.687 | INFO     | __main__:main:97 - Repository homepage is https://github.com/gbouras13/pharokka
    2025-08-11 11:35:43.687 | INFO     | __main__:main:98 - Written by George Bouras: george.bouras@adelaide.edu.au
    2025-08-11 11:35:43.687 | INFO     | __main__:main:100 - Checking database installation in pharokka_db.
    2025-08-11 11:35:43.688 | INFO     | __main__:main:103 - All databases have been successfully checked.
    2025-08-11 11:35:43.688 | INFO     | __main__:main:119 - Checking dependencies.
    Traceback (most recent call last):
      File "/home/runner/_work/modules/modules/.nf-test/tests/f4ff6f3ff2c31cdd0ae0bfea1540e4f4/work/conda/env-59d3ccaaf552043f-38590c47211f7272b7570db0336b1682/bin/pharokka.py", line 489, in <module>
        main()
      File "/home/runner/_work/modules/modules/.nf-test/tests/f4ff6f3ff2c31cdd0ae0bfea1540e4f4/work/conda/env-59d3ccaaf552043f-38590c47211f7272b7570db0336b1682/bin/pharokka.py", line 128, in main
        ) = check_dependencies(args.skip_mash)
      File "/home/runner/_work/modules/modules/.nf-test/tests/f4ff6f3ff2c31cdd0ae0bfea1540e4f4/work/conda/env-59d3ccaaf552043f-38590c47211f7272b7570db0336b1682/bin/input_commands.py", line 379, in check_dependencies
        phanotate_major_version = int(phanotate_version.split(".")[0])
    ValueError: invalid literal for int() with base 10: '/home/runner/_work/modules/modules/'
```

**Comment by awgymer** [comment]
I don't think that issue is related to touching empty `.gz` files is it? That seems like a case where the tool is actually being run?

**Comment by famosab** [comment]
True, my bad I messed with the large PR and got lost where to put the errors I encountered! I will just leave it here so if anyone updates pharokka they might find it :)

**Comment by vagkaratzas** [comment]
Found 19 modules with erroneous touch on .gz files:                                                            
                                                                                                                 
  - bcftools/split                                                                                               
  - bowtie2/align                                                                                                
  - clustalo/align                                                                                               
  - famsa/align <- I fixed this one                                                                                                 
  - gatk4/haplotypecaller                                                                                        
  - getorganelle/fromreads                                                                                       
  - kalign/align                                                                                                 
  - metamdbg/asm                                                                                                 
  - mtmalign/align
  - muscle5/super5
  - pharokka/installdatabases
  - popscle/freemuxlet
  - rastair/methylkit
  - ripgrep
  - staramr/search
  - tcoffee/align
  - tcoffee/consensus
  - tcoffee/regressive
  - vt/decomposeblocksub

  Note: clustalo/align, famsa/align, kalign/align, mtmalign/align, muscle5/super5, tcoffee/* conditionally touch
  .gz (when compress is true) — still erroneous. The fix in all cases should be echo '' | gzip > file.gz instead
  of touch file.gz.
