### ISSUE TITLE
nf-test (modules/nf-core/pharokka/pharokka, conda) fails

### ISSUE THREAD

**Issue by GallVp** [nf-core/modules#6152]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

Test Process PHAROKKA_PHAROKKA

  Test [6dbe844a] 'sarscov2 - genome - fasta' 
    > N E X T F L O W  ~  version 24.04.4
    > Launching `/home/ubuntu/tests/6dbe844a004a70ff2a3a2f4c1371d4af/meta/mock.nf` [special_chandrasekhar] DSL2 - revision: a0fa29442c
    > Creating env using conda: /opt/actions-runner/_work/modules/modules/modules/nf-core/pharokka/pharokka/tests/../../installdatabases/environment.yml [cache /home/ubuntu/tests/6dbe844a004a70ff2a3a2f4c1371d4af/work/conda/pharokka_installdatabases-4a97adf9dce8e6510a265f9534fc6dfe]
    > [4b/a0fe24] Submitted process > PHAROKKA_INSTALLDATABASES
    > ERROR ~ Error executing process > 'PHAROKKA_INSTALLDATABASES'
    > 
    > Caused by:
    >   Process `PHAROKKA_INSTALLDATABASES` terminated with an error exit status (1)
    > 
    > 
    > Command executed:
    > 
    >   install_databases.py \
    >       --outdir pharokka_db \
    >   
    >   
    >   cat <<-END_VERSIONS > versions.yml
    >   "PHAROKKA_INSTALLDATABASES":
    >       pharokka: $(pharokka.py --version)
    >   END_VERSIONS
    > 
    > Command exit status:
    >   1
    > 
    > Command output:
    >   (empty)
    > 
    > Command error:
    >   Traceback (most recent call last):
    >     File "/home/ubuntu/tests/6dbe844a004a70ff2a3a2f4c1371d4af/work/conda/pharokka_installdatabases-4a97adf9dce8e6510a265f9534fc6dfe/bin/install_databases.py", line 7, in <module>
    >       from databases import instantiate_install
    >     File "/home/ubuntu/tests/6dbe844a004a70ff2a3a2f4c1371d4af/work/conda/pharokka_installdatabases-4a97adf9dce8e6510a265f9534fc6dfe/bin/databases.py", line 32, in <module>
    >       from post_processing import remove_directory
    >     File "/home/ubuntu/tests/6dbe844a004a70ff2a3a2f4c1371d4af/work/conda/pharokka_installdatabases-4a97adf9dce8e6510a265f9534fc6dfe/bin/post_processing.py", line 12, in <module>
    >       from Bio.SeqUtils import GC
    >   ImportError: cannot import name 'GC' from 'Bio.SeqUtils' (/home/ubuntu/tests/6dbe844a004a70ff2a3a2f4c1371d4af/work/conda/pharokka_installdatabases-4a97adf9dce8e6510a265f9534fc6dfe/lib/python3.12/site-packages/Bio/SeqUtils/__init__.py)
    > 
    > Work dir:
    >   /home/ubuntu/tests/6dbe844a004a70ff2a3a2f4c1371d4af/work/4b/a0fe24adf4a2d7f98080159ab6e8fa
    > 
    > Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
    > 
    >  -- Check '/home/ubuntu/tests/6dbe844a004a70ff2a3a2f4c1371d4af/meta/nextflow.log' file for details
    > WARN: Got an interrupted exception while taking agent result | java.lang.InterruptedException
Assertion failed: 

assert process.success
       |       |
       |       false
       PHAROKKA_PHAROKKA

**Comment by GallVp** [comment]
Seems to have been fixed by a module version bump!
