### ISSUE TITLE
nf-test (modules/nf-core/learnmsa/align, conda) fails

### ISSUE THREAD

**Issue by GallVp** [nf-core/modules#6185]
### Have you checked the docs?

- [X] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [X] [nf-core modules documentation](https://nf-co.re/docs/contributing/modules)

### Description of the bug

Test Process LEARNMSA_ALIGN

  Test [4f4530da] 'sarscov2 - fasta - uncompressed' 
    > N E X T F L O W  ~  version 24.04.4
    > Launching `/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/meta/mock.nf` [dreamy_golick] DSL2 - revision: e6211c18ad
    > Creating env using conda: /opt/actions-runner/_work/modules/modules/modules/nf-core/learnmsa/align/tests/../environment.yml [cache /home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662]
    > [45/14412b] Submitted process > LEARNMSA_ALIGN (test)
    > ERROR ~ Error executing process > 'LEARNMSA_ALIGN (test)'
    > 
    > Caused by:
    >   Process `LEARNMSA_ALIGN (test)` terminated with an error exit status (1)
    > 
    > 
    > Command executed:
    > 
    >   learnMSA \
    >        \
    >       -i <(unpigz -cdf informative_sites.fas) \
    >       -o test.aln
    >   
    >   cat <<-END_VERSIONS > versions.yml
    >   "LEARNMSA_ALIGN":
    >       learnmsa: $(learnMSA -h | grep 'version' | awk -F 'version ' '{print $2}' | awk '{print $1}' | sed 's/)//g')
    >       pigz: $(echo $(pigz --version 2>&1) | sed 's/^.*pigz\w*//' ))
    >   END_VERSIONS
    > 
    > Command exit status:
    >   1
    > 
    > Command output:
    >   learnMSA (version 2.0.1) - multiple alignment of protein sequences
    > 
    > Command error:
    >   Traceback (most recent call last):
    >   learnMSA (version 2.0.1) - multiple alignment of protein sequences
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/bin/learnMSA", line 11, in <module>
    >       sys.exit(run_main())
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/learnMSA/run/console.py", line 105, in run_main
    >       from ..msa_hmm import Configuration, Initializers, Align, Emitter, Training, Visualize
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/learnMSA/msa_hmm/Configuration.py", line 3, in <module>
    >       import tensorflow as tf
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/tensorflow/__init__.py", line 51, in <module>
    >       from ._api.v2 import compat
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    >       from . import v1
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    >       from . import compat
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 37, in <module>
    >       from . import v1
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/compat/v1/__init__.py", line 47, in <module>
    >       from tensorflow._api.v2.compat.v1 import lite
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/lite/__init__.py", line 9, in <module>
    >       from . import experimental
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/lite/experimental/__init__.py", line 8, in <module>
    >       from . import authoring
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/lite/experimental/authoring/__init__.py", line 8, in <module>
    >       from tensorflow.lite.python.authoring.authoring import compatible
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/tensorflow/lite/python/authoring/authoring.py", line 43, in <module>
    >       from tensorflow.lite.python import convert
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/tensorflow/lite/python/convert.py", line 28, in <module>
    >       from tensorflow.lite.python import util
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/tensorflow/lite/python/util.py", line 55, in <module>
    >       from jax import xla_computation as _xla_computation
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/jax/__init__.py", line 139, in <module>
    >       from jax import nn as nn
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/jax/nn/__init__.py", line 19, in <module>
    >       from jax._src.nn.functions import (
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/jax/_src/nn/functions.py", line 30, in <module>
    >       from jax.scipy.special import expit
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/jax/scipy/__init__.py", line 16, in <module>
    >       from jax.scipy import linalg as linalg
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/jax/scipy/linalg.py", line 15, in <module>
    >       from jax._src.scipy.linalg import (
    >     File "/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/conda/learnmsa_align-ee2a61efe198b1c36f5d3f63db677662/lib/python3.10/site-packages/jax/_src/scipy/linalg.py", line 283, in <module>
    >       @_wraps(scipy.linalg.tril)
    >   AttributeError: module 'scipy.linalg' has no attribute 'tril'
    > 
    > Work dir:
    >   /home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/work/45/14412bbd033c3010ce2ea87aec0dfe
    > 
    > Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
    > 
    >  -- Check '/home/ubuntu/tests/4f4530da6a90367fbb049e5d4326a1ba/meta/nextflow.log' file for details
    > WARN: Got an interrupted exception while taking agent result | java.lang.InterruptedException
Assertion failed: 

assert process.success
       |       |
       |       false
       LEARNMSA_ALIGN

**Comment by luisas** [comment]
This module does not have conda support :/ How should we handle it? @GallVp

Should we close this issue or  rename it into add conda support for learnMSA align? The authors are not recommending running on conda currently
